### ISSUE TITLE
Duplicate replies

### ISSUE THREAD

**Issue by chrisatomix** [ocean/hubot-tucker#1]
`> @hubot Malcolm Tucker`
Responds with two quotes because it matches both words (unless HUBOT_LESS_MALCOLM has been set)

**Comment by ocean** [comment]
Hi Chris, I've noted this bug on our installation and have been meaning to fix it, sorry.

Thanks for prompting me! :-)

Cheers,
Drew

**Comment by chrisatomix** [comment]
My pleasure! May send some PR's if I get time, but it's too busy at the moment.

Thanks for releasing this!

**Comment by ocean** [comment]
Fixed! And published, thanks Chris. I can blame the GitHub outage for a little bit of the delay :smiley:

**Comment by ocean** [comment]
Premature closing, whoops :-)

I fixed the bug but it was only fixed in some Hubot adapters, hopefully it's fixed properly now in the latest release, 1.5.5.
