### ISSUE TITLE
Feature Request: Option to add Byline

### ISSUE THREAD

**Issue by chrisatomix** [ocean/hubot-tucker#2]
For teams with users who don't know who Malcolm Tucker is, it might be helpful to have a configuration option that adds a byline to all the quotes.

Perhaps something like:
`hubot: 'I could always go and fire a warning shot across his throat.' - Malcolm Tucker`

**Comment by ocean** [comment]
Nice idea. I'll have a look at it.

I'd like to have the name link to Wikipedia too, but not all (most maybe?) Hubot-compatible chat clients don't support HTML messages :/

**Comment by ocean** [comment]
Added this and published. The env var is HUBOT_TUCKER_BYLINE, details in README.

Cheers,
Drew
